#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$DIR")"

source ${DIR}/_tty.sh

docker_run --init \
	--entrypoint=npm \
	-v npm-cache:/root/npm \
	-v "$PROJECT_ROOT":"$PROJECT_ROOT" \
	-w "$(pwd)" \
	mangoweb/mango-cli:v3.5.0 "$@"


